name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Checkout LLVM
      uses: actions/checkout@v3
      with:
        repository: llvm/llvm-project
        ref: ${{ github.workspace }}/llvm-sha.txt
        path: llvm-project

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build clang-format clang-tidy

    - name: Update from llvm-project
      run: |
        python scripts/update.py llvm-project/ .

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/cmake_build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DLLVM_ADT_ENABLE_TESTS=ON \ 
          -G Ninja

    - name: Build
      run: cmake --build ${{ github.workspace }}/cmake_build --config ${{ matrix.build_type }}

    - name: Run tests
      run: cmake --build ${{ github.workspace }}/cmake_build --config ${{ matrix.build_type }} --target check-llvm-adt
