name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/cmake_build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DLLVM_ADT_ENABLE_TESTS=ON \
          -G Ninja

    - name: Build
      run: cmake --build ${{ github.workspace }}/cmake_build --config ${{ matrix.build_type }}

    - name: Run tests
      run: cmake --build ${{ github.workspace }}/cmake_build --config ${{ matrix.build_type }} --target check-llvm-adt

    - name: Get LLVM commit
      id: llvm-commit
      run: echo "commit=$(cat llvm-sha.txt)" >> $GITHUB_OUTPUT

    - name: Checkout LLVM
      uses: actions/checkout@v4
      with:
        repository: llvm/llvm-project
        ref: ${{ steps.llvm-commit.outputs.commit }}
        path: llvm-project

    - name: Update from llvm-project
      run: |
        python scripts/update.py llvm-project/ .

    - name: Build updated
      run: cmake --build ${{ github.workspace }}/cmake_build --config ${{ matrix.build_type }}

    - name: Run tests updated
      run: cmake --build ${{ github.workspace }}/cmake_build --config ${{ matrix.build_type }} --target check-llvm-adt
